[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[build]
publish = "."
# تأكد من أن كل أمر في سطر منفصل
# هذا سيضمن تنفيذ npm install بشكل كامل قبل محاولة بناء الوظائف
command = "npm install\nnpm run build:functions" # تم تعديل الأمر هنا